### ISSUE TITLE
Phosphor url error

### ISSUE THREAD

**Issue by cacolar-work** [lekoala/last-icon#1]
There is no type at the end of the file name.
https://cdn.jsdelivr.net/gh/phosphor-icons/phosphor-icons@1.4.1/assets/regular/

**Comment by lekoala** [comment]
well, there is for any other type (duotone, regular, etc)
thanks them for inconsistent naming :)

i've allowed the paths to be set as functions for these situations
https://github.com/lekoala/last-icon/releases/tag/2.0.3
